version: "v1.4.1" # 当前版本，如程序存在问题可修改此处并运行程序，将下载的安装程序覆盖安装尝试修复
configVersion: "1.0.0"
server: "https://qn.nya-wsl.cn/scu/" # 末尾的“/”需保留，资源服务器url
host: "150.158.171.157" # 语录服务器
port: 21 # ftp端口

Url:
  sentencesUrl: "http://sentence.osttsstudio.ltd:9000/" # 末尾的“/”需保留，语录系统的前端url

Account:
  user: "" # 请联系我们获取
  passwd: "" # 请联系我们获取

Path:
  updatePath: "scu_update.exe" # 保持默认，仅为方便后续更新，如随意修改可能将导致无法更新
  logPath: "logs"
  delJson: "*.json" # 保持默认，需删除的本地残留语录文件
  versionFile: "version.html" # 保持默认，版本号获取所需
  

Sentences:
  a: "桑吉" # 可自定义，但保存的语录依然是桑吉语录，下方同理
  b: "羽月"
  c: "楠桐"

UI:
  # 关于不能自定义初始窗口大小的问题：因为canvas里的每个元素的xy都是写死的，如果改了大小需要重新算位置，避免组件显示错位暂不支持自定义，如有需要可修改源码
  backgroundColor: "#FFE0E0" # 背景颜色
  font: "Inter Regular" # 测试功能，暂不清楚修改此处是否有效，仅支持本地字体，如有问题留空或保持默认即可